#!/usr/bin/env ruby
this_dir = File.expand_path(File.dirname(__FILE__))
lib_dir = File.join(this_dir, '..', 'lib', 'svc')
$LOAD_PATH.unshift(lib_dir)

require 'grpc'
require 'mather'

def main
  s = GRPC::RpcServer.new
  s.add_http2_port('0.0.0.0:30000', :this_port_is_insecure)
  s.handle(MatherServer)
  s.run_till_terminated_or_interrupted([1, 'int', 'SIGQUIT'])
end

main
