#!/usr/bin/env ruby
this_dir = File.expand_path(File.dirname(__FILE__))
lib_dir = File.join(this_dir, '..', '..', 'src', 'svc')
$LOAD_PATH.unshift(lib_dir)

require 'rubygems'
require 'bundler/setup'
require 'grpc'
require 'mather'
require 'commander'

class MatherServer
  include Commander::Methods

  def run
    program :name, 'Mather Server (in Ruby)'
    program :version, '1.0.0'
    program :description,
            'Simple Ruby gRPC microservice that does math.'

    command :start do |c|
      c.syntax = 'mather-rb-server start'
      c.description = 'Starts the server'
      c.option '--port PORT', String, "Server's port (default \":30000\")"

      c.action do |args, options|
        port = options.port || ':30000'

        s = GRPC::RpcServer.new
        s.add_http2_port("0.0.0.0#{port}", :this_port_is_insecure)
        s.handle(MatherService)

        puts "Server started on port #{port}"
        s.run_till_terminated_or_interrupted([1, 'int', 'SIGQUIT'])
      end
    end

    run!
  end
end

MatherServer.new.run
